services:
  db:
    image: postgres
    env_file:
      - ./backend/.env
    ports:
      - "5431:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres-data:
