services:
  db:
    image: postgres
    env_file:
      - ./backend/.env
    ports:
      - "5431:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # app:
  #   build: ./backend/
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./backend:/app
  #   depends_on:
  #     - db
  #   env_file:
  #     - ./backend/.env
volumes:
  postgres-data:
